spring:
  application:
    name: movierama
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movierama
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  port: 8080