spring:
  application:
    name: movierama
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/movierama
    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: jdbc:h2:mem:movieramaDB
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
#      database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081